import React from 'react'
import { useState } from 'react'
import axios from 'axios'
const Dashboard = () => {
  const [email,setEmail]=useState("")
  const [subject,setSubject]=useState("")
  // const [message,setMessage]=useState("")
  const [text,setText]=useState("")
  const handlesubmit=async()=>{
    try{
const res=await axios.post("http://localhost:4000/req/send/email",{
email,subject,text
},{
  withCredentials:true
})
console.log(res.data.message)
console.log(res.data.info)
}
catch(err){
  console.log("err",err)
}
  }
  return (
    <div>
      <p>Welcome to the Tonify</p>
    To:<input type='email' placeholder='Enter Email to send ' onChange={(e)=>{setEmail(e.target.value)}}></input>
    Subject:<textarea onChange={(e)=>{setSubject(e.target.value)}}></textarea>
    Message:<textarea onChange={(e)=>{setText(e.target.value)}}></textarea>
    <button onClick={handlesubmit}>Send-Email</button>
    </div>
  )
}

export default Dashboard
// nsivasai88@gmail.com
// hello from tonify
// this was autogenerated email