// import React from 'react'
// import { useState } from 'react'
// import axios from 'axios'
// const Dashboard = () => {
//   const [email,setEmail]=useState("")
//   const [subject,setSubject]=useState("")
//   // const [message,setMessage]=useState("")
//   const [text,setText]=useState("")
//   const handleedit=()=>{
//     setEmail("")
//     setSubject("")
//     setText("")
//   }
//   const handlerecipt=()=>{
//     console.log("hello")
//     <p>Conformation</p>,
//     <p>To:{email}</p>,
//     <p>Subject:{subject}</p>,
//     <p>Text:{text}</p>,
//     <button onClick={handleedit}>Edit</button>,
//     <button onClick={handlesubmit}>sendMail</button>
//   }
//   const handlesubmit=async()=>{
//     try{
// const res=await axios.post("http://localhost:4000/req/send/email",{
// email,subject,text
// },{
//   withCredentials:true
// })
// console.log(res.data.message)
// console.log(res.data.info)
// }
// catch(err){
//   console.log("err",err)
// }
//   }
//   return (
//     <div>
//       <p>Welcome to the Tonify</p>
//     To:<input type='email' placeholder='Enter Email to send ' value={email} onChange={(e)=>{setEmail(e.target.value)}}></input>
//     Subject:<textarea value={subject} onChange={(e)=>{setSubject(e.target.value)}}></textarea>
//     Message:<textarea value={text} onChange={(e)=>{setText(e.target.value)}}></textarea>
//     <button onClick={handlerecipt}>Conform</button>
//     {/* <button onClick={handlesubmit}>Send-Email</button> */}
//     </div>
//   )
// }

// export default Dashboard
// nsivasai88@gmail.com
// hello from tonify
// this was autogenerated email

import React, { useState } from "react";
import axios from "axios";
import "../controls/dashboard.css"
import word from "../assets/word.png"
const Dashboard = () => {
  const [email, setEmail] = useState("");
  const [subject, setSubject] = useState("");
  const [text, setText] = useState("");
  const [showPopup, setShowPopup] = useState(false);
  const [valid,setValid]=useState(false)
  //   const isValidEmail = (email) => {
  //   const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  //   const result= regex.test(email);
  //   console.log(result)
  //   setValid(result)
  // };
  const handleEdit = () =>{
    setShowPopup(false); 
  };
  const handlerecipt = () => {
  if (!email || !subject || !text) {
  setShowPopup(false);
  return alert("Please fill all fields before confirming!");
}
// isValidEmail(email)
// if(isValidEmail==false){
//   console.log("unable to send email")
//   setShowPopup(false);
// return alert("please Enter the valid Email")
// }
  setShowPopup(true);

  };
  const handleai=async()=>{
    // console.log("hello bro  iam from ai email")
    const res=await axios.post("http://localhost:4000/prompt/message",{
      text
    })
    console.log(res.data.message)

  }

  const handlesubmit = async () => {
    try {
      const res = await axios.post(
        "http://localhost:4000/req/send/email",
        { email, subject, text },
        { withCredentials: true }
      );
      console.log(res.data.message);
      console.log(res.data.info);
      setShowPopup(false); 
    } catch (err) {
      console.log("err", err);
    }
  };

  return (
    <div>
      <p>Welcome to the Tonify</p>
      To:
      <input
        type="email"
        placeholder="Enter Email"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
      />
      <br />
      Subject:
      <textarea
        value={subject}
        onChange={(e) => setSubject(e.target.value)}
      ></textarea>
      <br />
      Message:
      <textarea
        value={text}
        onChange={(e) => setText(e.target.value)}
      ></textarea>
     <div className="gettouch"><img src={word} alt="AI-mail" onClick={handleai}></img></div>
      <br />
      <button onClick={handlerecipt}>Confirm</button>

      {/* Popup Modal */}
      {showPopup && (
        <div
          style={{
            position: "fixed",
            top: 0,
            left: 0,
            width: "100vw",
            height: "100vh",
            backgroundColor: "rgba(0,0,0,0.5)",
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
          }}
        >
          <div
            style={{
              background: "white",
              padding: "20px",
              borderRadius: "10px",
              width: "400px",
              textAlign: "center",
            }}
          >
            <h3>Confirmation</h3>
            <p>
              <b>To:</b> {email}
            </p>
            <p>
              <b>Subject:</b> {subject}
            </p>
            <p>
              <b>Message:</b> {text}
            </p>
            <div style={{ marginTop: "15px" }}>
              <button onClick={handleEdit} style={{ marginRight: "10px" }}>
                Edit
              </button>
              <button onClick={handlesubmit}>Send-Mail</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default Dashboard; 
